{
  "Class": "vulnerability",
  "ID": "oval:com.redhat.unaffected:def:201911324",
  "Version": "631",
  "Metadata": {
    "Title": "Unaffected components for: CVE-2019-11324 python-urllib3: Certification mishandle when error should be thrown (moderate)",
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2019-11324",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2019-11324"
      }
    ],
    "Description": "Red Hat's versions of the associated software have been determined to NOT be affected by CVE-2019-11324.",
    "Advisory": {
      "From": "secalert@redhat.com",
      "Severity": "Moderate",
      "Issued": {},
      "Updated": {}
    }
  },
  "Criteria": {
    "Operator": "OR",
    "Criterions": [
      {
        "Comment": "Red Hat Enterprise Linux must be installed",
        "TestRef": "oval:com.redhat.cve:tst:20022439072"
      }
    ],
    "Criterias": [
      {
        "Operator": "AND",
        "Criterions": [
          {
            "Comment": "Red Hat Enterprise Linux 6 is installed",
            "TestRef": "oval:com.redhat.cve:tst:20022439071"
          },
          {
            "Comment": "python-urllib3 is installed",
            "TestRef": "oval:com.redhat.cve:tst:201820060001"
          },
          {
            "Comment": "python-urllib3 is not installed",
            "TestRef": "oval:com.redhat.unaffected:tst:201911324002"
          }
        ]
      }
    ]
  }
}