{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2020-25690",
  "PublicDate": "2020-11-02T00:00:00Z",
  "References": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25690",
    "https://bugzilla.redhat.com/show_bug.cgi?id=1893188"
  ],
  "Description": "[Unknown description]",
  "UbuntuDescription": "",
  "Notes": [
    "amurray| This is a Red Hat specific CVE due to an insufficient backport of the upstream patch in CVE-2020-5395. Since that CVE is not yet patched in Ubuntu, I am adding this CVE to be tracked so we don't make the same mistake."
  ],
  "Bugs": null,
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "",
  "Patches": {
    "fontforge": {
      "bionic": {
        "Status": "needs-triage",
        "Note": ""
      },
      "devel": {
        "Status": "needs-triage",
        "Note": ""
      },
      "focal": {
        "Status": "needs-triage",
        "Note": ""
      },
      "groovy": {
        "Status": "needs-triage",
        "Note": ""
      },
      "precise/esm": {
        "Status": "DNE",
        "Note": ""
      },
      "trusty": {
        "Status": "ignored",
        "Note": "out of standard support"
      },
      "trusty/esm": {
        "Status": "DNE",
        "Note": ""
      },
      "upstream": {
        "Status": "not-affected",
        "Note": "debian: Insufficient patch for CVE-2020-5395 not applied"
      },
      "xenial": {
        "Status": "needs-triage",
        "Note": ""
      }
    }
  },
  "UpstreamLinks": {}
}