{
  "debianbug": 710597,
  "description": "bson/_cbsonmodule.c in the mongo-python-driver (aka. pymongo) before 2.5.2, as used in MongoDB, allows context-dependent attackers to cause a denial of service (NULL pointer dereference and crash) via vectors related to decoding of an \"invalid DBRef.\"",
  "releases": {
    "bullseye": {
      "fixed_version": "2.5.2-1",
      "repositories": {
        "bullseye": "3.11.0-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "2.5.2-1",
      "repositories": {
        "buster": "3.7.1-1.1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "2.5.2-1",
      "repositories": {
        "sid": "3.11.0-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "2.5.2-1",
      "repositories": {
        "stretch": "3.4.0-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}