{
  "Class": "vulnerability",
  "ID": "oval:com.redhat.cve:def:20153206",
  "Version": "631",
  "Metadata": {
    "Title": "CVE-2015-3206 python-kerberos: checkPassword() does not verify KDC authenticity (moderate)",
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2015-3206",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2015-3206"
      }
    ],
    "Description": "STATEMENT: This issue affects the versions of python-kerberos as shipped with Red Hat Enterprise Linux 5, 6, and 7. Red Hat Product Security has rated this issue as having Moderate security impact. Additionally this issue is difficult to exploit in most common scenarios (due to the need for a valid Kerberos TGT)c For additional information, refer to the Issue Severity Classification: https://access.redhat.com/security/updates/classification/.",
    "Advisory": {
      "From": "secalert@redhat.com",
      "Severity": "Moderate",
      "Issued": {},
      "Updated": {}
    }
  },
  "Criteria": {
    "Operator": "OR",
    "Criterions": [
      {
        "Comment": "Red Hat Enterprise Linux must be installed",
        "TestRef": "oval:com.redhat.cve:tst:20022439072"
      }
    ],
    "Criterias": [
      {
        "Operator": "AND",
        "Criterions": [
          {
            "Comment": "Red Hat Enterprise Linux 6 is installed",
            "TestRef": "oval:com.redhat.cve:tst:20022439071"
          },
          {
            "Comment": "python-kerberos is installed",
            "TestRef": "oval:com.redhat.cve:tst:20153206001"
          },
          {
            "Comment": "python-kerberos is signed with Red Hat redhatrelease2 key",
            "TestRef": "oval:com.redhat.cve:tst:20153206002"
          }
        ]
      }
    ]
  }
}