{
  "Class": "vulnerability",
  "ID": "oval:com.redhat.cve:def:20172810",
  "Version": "631",
  "Metadata": {
    "Title": "CVE-2017-2810 python-tablib: Databook loading functionality allows command execution (low)",
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2017-2810",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2017-2810"
      }
    ],
    "Description": "DOCUMENTATION: It was found that loading a yaml format Databook from an untrusted source could lead to arbitrary code execution in python-tablib as the safe_load method was not used to load the content.\n            STATEMENT: Red Hat Product Security has rated this issue as having Low security impact in Red Hat OpenStack Platform. While the code is present in the python-tablib package, it is not reachable in any supported configuration. There is currently no plan to address this flaw in any supported version of Red Hat OpenStack platform.",
    "Advisory": {
      "From": "secalert@redhat.com",
      "Severity": "Low",
      "Issued": {},
      "Updated": {}
    }
  },
  "Criteria": {
    "Operator": "OR",
    "Criterions": [
      {
        "Comment": "Red Hat Enterprise Linux must be installed",
        "TestRef": "oval:com.redhat.cve:tst:20137458006"
      }
    ],
    "Criterias": [
      {
        "Operator": "AND",
        "Criterions": [
          {
            "Comment": "Red Hat Enterprise Linux 7 is installed",
            "TestRef": "oval:com.redhat.cve:tst:20137458005"
          },
          {
            "Comment": "python-tablib is installed",
            "TestRef": "oval:com.redhat.cve:tst:20172810001"
          },
          {
            "Comment": "python-tablib is signed with Red Hat redhatrelease2 key",
            "TestRef": "oval:com.redhat.cve:tst:20172810002"
          }
        ]
      }
    ]
  }
}