{
  "Class": "vulnerability",
  "ID": "oval:com.redhat.cve:def:202013757",
  "Version": "631",
  "Metadata": {
    "Title": "CVE-2020-13757 python-rsa: decryption of ciphertext leads to DoS (moderate)",
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2020-13757",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2020-13757"
      }
    ],
    "Description": "DOCUMENTATION: A flaw was found in the python-rsa package, where it does not explicitly check the ciphertext length against the key size and ignores the leading 0 bytes during the decryption of the ciphertext. This flaw allows an attacker to perform a ciphertext attack, leading to a denial of service. The highest threat from this vulnerability is to confidentiality.",
    "Advisory": {
      "From": "secalert@redhat.com",
      "Severity": "Moderate",
      "Issued": {},
      "Updated": {}
    }
  },
  "Criteria": {
    "Operator": "OR",
    "Criterions": [
      {
        "Comment": "Red Hat Enterprise Linux must be installed",
        "TestRef": "oval:com.redhat.cve:tst:20161000107044"
      }
    ],
    "Criterias": [
      {
        "Operator": "AND",
        "Criterions": [
          {
            "Comment": "Red Hat Enterprise Linux 8 is installed",
            "TestRef": "oval:com.redhat.cve:tst:20161000107043"
          },
          {
            "Comment": "python3-rsa is installed",
            "TestRef": "oval:com.redhat.cve:tst:202013757001"
          },
          {
            "Comment": "python3-rsa is signed with Red Hat redhatrelease2 key",
            "TestRef": "oval:com.redhat.cve:tst:202013757002"
          }
        ]
      }
    ]
  }
}