{
  "ID": "oval:org.debian:def:20021119",
  "Class": "vulnerability",
  "Metadata": {
    "Title": "CVE-2002-1119",
    "AffectedList": [
      {
        "Family": "unix",
        "Platform": "Debian GNU/Linux 10",
        "Product": "python"
      }
    ],
    "References": null,
    "Description": "insecure temporary files",
    "Debian": {
      "MoreInfo": "\nDSA-159\nZack Weinberg discovered an insecure use of a temporary file in\nos._execvpe from os.py.  It uses a predictable name which could lead\nexecution of arbitrary code.\nThis problem has been fixed in several versions of Python: For the\ncurrent stable distribution (woody) it has been fixed in version\n1.5.2-23.1 of Python 1.5, in version 2.1.3-3.1 of Python 2.1 and in\nversion 2.2.1-4.1 of Python 2.2.  For the old stable distribution\n(potato) this has been fixed in version 1.5.2-10potato12 for Python\n1.5.  For the unstable distribution (sid) this has been fixed in\nversion 1.5.2-24 of Python 1.5, in version 2.1.3-6a of Python 2.1 and\nin version 2.2.1-8 of Python 2.2.  Python 2.3 is not affected by this\nproblem.\nWe recommend that you upgrade your Python packages immediately.\n"
    }
  },
  "Criteria": {
    "Operator": "AND",
    "Criterias": [
      {
        "Operator": "OR",
        "Criterias": [
          {
            "Operator": "AND",
            "Criterias": null,
            "Criterions": [
              {
                "Negate": false,
                "TestRef": "oval:org.debian.oval:tst:2",
                "Comment": "all architecture"
              },
              {
                "Negate": false,
                "TestRef": "oval:org.debian.oval:tst:88",
                "Comment": "Python DPKG is earlier than 1.5.2-24"
              }
            ]
          }
        ],
        "Criterions": null
      }
    ],
    "Criterions": [
      {
        "Negate": false,
        "TestRef": "oval:org.debian.oval:tst:1",
        "Comment": "Debian 10 is installed"
      }
    ]
  }
}